"""initial_migration

Revision ID: 1eb232baef70
Revises: 
Create Date: 2026-05-07 21:11:46.632725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1eb232baef70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # COMMENTÉ POUR ÉVITER LA PERTE DE DONNÉES
    # op.drop_table('niveaux_validation')
    # op.drop_table('documents')
    # op.drop_table('validations_document')
    # op.drop_table('entreprises')
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('email'))
    # op.drop_table('users')
    # op.drop_table('notifications')
    # op.drop_table('logs')
    pass  # Ne rien faire - les tables existent déjà
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Cette fonction n'est pas utilisée pour l'instant
    pass
    # ### end Alembic commands ###